### PR TITLE
Adds support for HTTPS & Basic Auth by changing the initialization semantics of the node client

### LINKED ISSUE #18: Add support for basic authentication
1) A lot of Elasticsearch as a service providers now use es-jetty or nginx to provide basic authN ... so it would be pretty cool if we could control specify username password for basic authN in the node.js for elastic.js client.
http://stackoverflow.com/questions/16137919/how-to-specify-credentials-username-password-for-elasticjs-client

2) I don't see a way to specify https either, so I'm guessing that the ability to specify that will have to be exposed as well?

### PR DESCRIPTION
**Pull request by svperfecta**
Hey @mattweber I hope this is cool.  I had a bit of time tonight and made a patch that seems to fix #18 and #18

Cheers!
Brian

### CODE REVIEW

**Comment by svperfecta** [comment]
@pulkitsinghal Could you give this a test on your HTTPS use case?  I couldn't get one working right locally.

**Comment by pulkitsinghal** [comment]
Sure, I'll get it to you 2morrow

**Comment by svperfecta** [comment]
Guys - I pushed the wrong version last night (we were in the middle of a hackathon, I was tired)  This should look a bit better.

**Comment by pulkitsinghal** [comment]
@genexp This is going to sound super dumb but can you point me to the process for getting your changes into my node_modules folder so I may test it?

**Comment by svperfecta** [comment]
Hey - Not super dumb at all :)  I have to look this up every time myself!
 Anyways, the easiest way is to just add my fork to your packages.json file
in your project, and rerun npm install.  I should look like this:

`"elastic.js": "git://github.com/genexp/elastic.js.git",`

**Comment by pulkitsinghal** [comment]
Thanks, that got it installed in my test workspace.

Next Q: How do I change this call to make use of your changes?

```
/* setup client */
ejs.client = nc.NodeClient(process.env.ES_HOST, process.env.ES_PORT);
```

Also, do 6e048da and d2b9198 together make one full pull request?

**Comment by svperfecta** [comment]
Right, that would help!  Just change it to work like this:

```

/* setup client */
ejs.client = nc.NodeClient('https://user:password@someserver:port');

```

Username, port & password should be optional :)

**Comment by pulkitsinghal** [comment]
I tried:

```
/* setup client */
ejs.client = nc.NodeClient("https://username:password@hosted.es.com:9243/");
```

It errored out:

```
events.js:129                                                                                                                                              
    throw new Error('addListener only takes instances of Function');                                                                                       
          ^                                                                                                                                                
Error: addListener only takes instances of Function                                                                                                        
    at ClientRequest.EventEmitter.addListener (events.js:129:11)                                                                                           
    at Object.ejs.NodeClient.post (/var/lib/stickshift/519bc9d14382ec186d000260/app-root/data/504499/node_modules/elastic.js/elastic-node-client.js:177:15)
    at Object.ejs.Document.doIndex (/var/lib/stickshift/519bc9d14382ec186d000260/app-root/data/504499/node_modules/elastic.js/elastic.js:8997:33)          
    at uploadDocuments (/var/lib/stickshift/519bc9d14382ec186d000260/app-root/data/504499/elasticsearch/clients/elasticjs/vend2es_worker.js:45:9)          
    at Request.download [as _callback] (/var/lib/stickshift/519bc9d14382ec186d000260/app-root/data/504499/elasticsearch/clients/elasticjs/vend2es_worker.js
:88:13)                                                                                                                                                    
    at Request.init.self.callback (/var/lib/stickshift/519bc9d14382ec186d000260/app-root/data/504499/node_modules/request/index.js:142:22)                 
    at Request.EventEmitter.emit (events.js:91:17)                                                                                                         
    at Request.onResponse (/var/lib/stickshift/519bc9d14382ec186d000260/app-root/data/504499/node_modules/request/index.js:856:14)                         
    at Request.EventEmitter.emit (events.js:115:20)                                                                                                        
    at IncomingMessage.Request.onResponse.buffer (/var/lib/stickshift/519bc9d14382ec186d000260/app-root/data/504499/node_modules/request/index.js:808:12)
```

**Comment by svperfecta** [comment]
Can you try deleting the node_modules/elastic.js folder and redoing `npm
install`?  I don't get that error locally with the same URL.  I get:

```
Error: getaddrinfo ENOTFOUND
```

Which is expected because I can't hit that address :)

**Comment by svperfecta** [comment]
Can you actually try again?  I didn't initially grok the build system here.  I think this fixes it.

**Comment by mattweber** [comment]
Hey guys, I just wanted to say thanks for working on this.  I will have a look later today or this weekend.  Thanks!

**Comment by pulkitsinghal** [comment]
I have a working URL but now I get:

```
events.js:66                                                                                                                                                
        throw arguments[1]; // Unhandled 'error' event                                                                                                      
                       ^                                                                                                                                    
Error: socket hang up                                                                                                                                       
    at createHangUpError (http.js:1263:15)                                                                                                                  
    at Socket.socketOnEnd [as onend] (http.js:1351:23)                                                                                                      
    at TCP.onread (net.js:418:26)
```

When I run `curl -XGET https://hosted.es.com:9243/_search -u username:password` it works so I can't imagine what's wrong with using `https://username:password@hosted.es.com:9243` in the nodejs code.

@genexp I think there might be some subtle mistake in how the URL is being taken apart and processed, why don't you sign up for a free https + authN enabled account at Found ES (http://www.found.no/) and then you'll be able to test it and fix the code from your side too :)

I've evaluated many ES trials and "Found ES" is the best because they let you test the https and access-control in the trial itself.

**Comment by svperfecta** [comment]
Thanks for the tip!  Should be all set now, it works locally.

**Comment by svperfecta** [comment]
Yep, erase, npm install, try it out :)

**Comment by pulkitsinghal** [comment]
I tried `rm -rf node_modules/elastic.js/`and my `package.json` file has `"elastic.js": "git://github.com/genexp/elastic.js.git"` and I run `npm install` again ... but afterwards I still run into an error:

```
events.js:66                                                                                                                                                
        throw arguments[1]; // Unhandled 'error' event                                                                                                      
                       ^                                                                                                                                    
Error: socket hang up                                                                                                                                       
    at createHangUpError (http.js:1263:15)                                                                                                                  
    at Socket.socketOnEnd [as onend] (http.js:1351:23)                                                                                                      
    at TCP.onread (net.js:418:26)
```

**Comment by svperfecta** [comment]
Changed this line for you.. the comparator was wrong:

https://github.com/genexp/elastic.js/blob/master/elastic-node-client.js#L68

**Comment by hmalphettes** [comment]
Hi there, I am interested in this:
- forked @genexp master branch
- added support for the original NodeClient constructor API: new NodeClient(host, port) will work as usual
- added a testsuite

Here is the commit: https://github.com/hmalphettes/elastic.js/commit/6d479ffb7b85cdd061fae430f0c54e66221b1332

I hope this helps; let me know how to proceed.

**Comment by svperfecta** [comment]
Thank you @hmalphettes!

**Comment by mattweber** [comment]
Hi guys, thanks for the work on this PR.  I took bits and pieces from it, but ultimately decided to simplify things a bit.  Please test the new functionality in 349f5724.

```
ejs.client = nc.NodeClient()  // http localhost:9200
ejs.client = nc.NodeClient('myhost', '80') // http myhost:80
ejs.client = nc.NodeClient('myhost', '443', 'https') // https myhost:443
ejs.client.protocol('https'); // use https
```

Also support setting any request options available to the http or https request such as auth.

```
ejs.client = nc.NodeClient().option('auth', 'myuser:pass')
```

Let me know if you run into any issues.

**Pull request closed without merging**
